version: '3'
services:
  api:
    container_name: tcms_api
    build:
      context: .
      dockerfile: tools/docker/Dockerfile.api
    env_file:
      - src/api/app/.env
    ports:
      - '8000:8000'
    depends_on:
      - database
  database:
    container_name: tcms_database
    build:
      context: .
      dockerfile: tools/docker/Dockerfile.postgres
    env_file:
      - src/api/app/.env
    ports:
      - '5432:5432'
